# Práctica n°2 : Inferencia esdatística para una sola variable usando R

Notas del Curso Gestión de la calidad y control estadístico de procesos

** Ibeth Vergara Baquero**   
ivergara@uco.edu.co   
Universidad Católica de Oriente   
Facultad de ingenierías    
Rionegro, Colombia


> ** Objetivo de la práctica:** Desarrollar Scripts para realizar inferencia estadística para una variable en R.

**Bibliografía**.
> [t.test()](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/t.test.html)  


A continuación se presentará el taller propuesto para complementar los temas vistos en clase con la programación en R.

### Inferencia estadística
**1.** La resistencia a la presión interna de las botellas de cristal para envasar una bebida carbonatada es una característica importante de la calidad. La embotelladora desea saber si la resistencia a la presión es diferente de 175 psi. Por la experiencia anterior. El fabricante de las botellas le hace llegar un lote de estas botellas a la embotelladora, la cual está interesada en probar la hipótesis. Se selecciona una muestra aleatoria de 200 botellas, las cuales se colocan en una máquina de prueba de presión hidrostática que incrementa la presión dentro de la botella hasta que estalla. Los datos son enviados a usted en un archivo llamado "datosinf" para que usted haga el estudio.

In [8]:
#H0: mu=175 H1: mu!=175
x=read.csv("datosinf.csv", header=T)
test=t.test(x=x$Diametro, #Vector numérico que contiene las muestras de estudio 
       mu= 175,  # Valor numerico de la media que se desea probar
       conf.level = 0.95, 
       alternative = "two.sided") #Indica el tipo de la hipotesis alternativa. 
                                #Diferencia="two.sided", mayor:"greater", menor= "less" 

test


	One Sample t-test

data:  x$Diametro
t = -45.29, df = 199, p-value < 2.2e-16
alternative hypothesis: true mean is not equal to 175
95 percent confidence interval:
 169.8821 170.3092
sample estimates:
mean of x 
 170.0957 


*Como alpha es mayor que p-value se rechaza H0 y por tanto la resistencia a la presión es estadisticamente diferente de 175 psi*

**2.** Para el ejercicio anterior calcular el itervalo de confianza del 95%

In [10]:
summary(test) # indica la información que puedo extraer de la prueba

            Length Class  Mode     
statistic   1      -none- numeric  
parameter   1      -none- numeric  
p.value     1      -none- numeric  
conf.int    2      -none- numeric  
estimate    1      -none- numeric  
null.value  1      -none- numeric  
alternative 1      -none- character
method      1      -none- character
data.name   1      -none- character

In [11]:
test$conf.int # Intervalo de confianza del 95%

[1] 169.8821 170.3092
attr(,"conf.level")
[1] 0.95

**3.** Ahora se desea probar si la resistencia a la presión excede los 170 psi.

In [18]:
#H0: mu=175 H1: mu!=175
test2=t.test(x=x$Diametro, #Vector numérico que contiene las muestras de estudio 
       mu= 170,  # Valor numerico de la media que se desea probar
       conf.level = 0.95, 
       alternative = "greater") #Indica el tipo de la hipotesis alternativa. 
                                #Diferencia="two.sided", mayor:"greater", menor= "less" 

test2


	One Sample t-test

data:  x$Diametro
t = 0.88329, df = 199, p-value = 0.1891
alternative hypothesis: true mean is greater than 170
95 percent confidence interval:
 169.9167      Inf
sample estimates:
mean of x 
 170.0957 


*Como alpha es menor que vp se acepta la hipótesis nula, por tanto la resistencia media a presión es estadisticamente igual a 170* 

**Para los siguientes puntos trabajar con el data set de R llamado ChickWeight. Recuerde revisar la base de datos antes de trabajar**  

**4.** Una empresa dedicada a la cría de pollo para la venta está interesada en el aumento del peso de los pollos por lo que ha decidido utilizar diversas dietas para lograr su objetivo. El encargado de la empresa necesita, por temas de calidad, que el peso promedio de los pollos sea 122 sin tener en cuenta que tipo de dieta esta utilizando. ¿Qué puede concluir? 

**5.** Determine un intervalo de confianza del 95% para el punto anterior

**6.** El encargado de la empresa desea determinar si los pollos criados con la dieta 2 tienen un peso superior a los 122. ¿Que puede concluir? 

**7.** Se desea probar si el peso de los pollos con la dieta 3 es menor a 160 ¿Qué puede inferir?